"api":
  - changed-files:
      - any-glob-to-any-file: ["api/**"]

"backend":
  - changed-files:
      - any-glob-to-any-file: ["backend/**"]

"web":
  - changed-files:
      - any-glob-to-any-file: ["web/**"]

"cli":
  - changed-files:
      - any-glob-to-any-file: ["cli/**"]

"infra":
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile"
          - "**/.dockerignore"
          - "docker-compose*.yml"
          - "scripts/**"
          - ".pre-commit-config.yaml"

"ci":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "release-please-config.json"
          - ".release-please-manifest.json"

"documentation":
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]
